//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSiege.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContentsEntities : DbContext
    {
        public ContentsEntities()
            : base("name=ContentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarouselInfo> CarouselInfo { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Tags> News_Tags { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<Secure> Secure { get; set; }
        public virtual DbSet<Subsections> Subsections { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
    }
}
