//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSiege.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class damianlukasik3612_crystalsiegeEntities : DbContext
    {
        public damianlukasik3612_crystalsiegeEntities()
            : base("name=damianlukasik3612_crystalsiegeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarouselInfo> CarouselInfoes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Tags> News_Tags { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Secure> Secures { get; set; }
        public virtual DbSet<Subsection> Subsections { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
