//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSiege.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsection
    {
        public decimal Id { get; set; }
        public decimal SectionsId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string title_ang { get; set; }
        public string content_ang { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
