//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSiege.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CarouselTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarouselTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalSiege.Resources.CarouselTexts", typeof(CarouselTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;img src=&amp;#39;~/ Resources / Image / IMG_6418.jpg&amp;#39; data-color=&amp;#39;firebrick&amp;#39; alt=&amp;#39;Second Image&amp;#39;&amp;gt;&amp;lt; div class=&amp;#39;carousel-caption&amp;#39;&amp;gt;&amp;lt;h3&amp;gt;Jakub Orłowski&amp;lt;/h3&amp;gt;&amp;lt;span&amp;gt;Wiceprezes Stowarzyszenia Tribrony, pisarz amator, historyk i bronioznawsca.Jego najnowsza książka Kryształowe Oblężenie tom 2 obejmująca 2 części, doczekało się wielkiego rozgłosu, zbierający najlepsze recenzje krytyk&amp;#243;w.&amp;lt;/span&amp;gt;&amp;lt;/div&amp;gt;.
        /// </summary>
        public static string Slajd_1 {
            get {
                return ResourceManager.GetString("Slajd_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;div class=&amp;#39;item&amp;#39; &amp;gt;&amp;lt;img src = &amp;#39;~/Resources/Image/wargames___finished_by_ruhisu-da3mvwl.png&amp;#39; data-color = &amp;#39;firebrick&amp;#39; alt = &amp;#39;Second Image&amp;#39; &amp;gt;&amp;lt;div class=&amp;#39;carousel-caption&amp;#39;&amp;gt;&amp;lt;h3&amp;gt;Kryształowe Oblężenie&amp;lt;/h3&amp;gt;&amp;lt;span&amp;gt;Porywająca powieść fantasy osadzona w świecie My Little Pony: Przyjaźń to Magia, na tle II wojny światowej...&amp;lt;/span&amp;gt;&amp;lt;/div&amp;gt;&amp;lt;/div&amp;gt;.
        /// </summary>
        public static string Slajd_2 {
            get {
                return ResourceManager.GetString("Slajd_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;div class=&amp;#39;item&amp;#39; &amp;gt;&amp;lt;img src = &amp;#39;~/Resources/Image/royal_equestrian_navy_bb_88_song_of_evening_by_ruhisu-da2u8kz.png&amp;#39; data-color = &amp;#39;firebrick&amp;#39; alt = &amp;#39;Second Image&amp;#39; &amp;gt;&amp;lt;div class=&amp;#39;carousel-caption&amp;#39;&amp;gt;&amp;lt;h3&amp;gt;Ruhisu&amp;lt;/h3&amp;gt;&amp;lt;span&amp;gt;Gł&amp;#243;wny Ilustrator książki oraz jeden z najlepszych artyst&amp;#243;w w polskim fandomie.&amp;lt;/span&amp;gt;&amp;lt;/div&amp;gt;&amp;lt;/div&amp;gt;.
        /// </summary>
        public static string Slajd_3 {
            get {
                return ResourceManager.GetString("Slajd_3", resourceCulture);
            }
        }
    }
}
