//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSiege.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalSiege.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcje.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne hasło.
        /// </summary>
        public static string ActualPassword {
            get {
                return ResourceManager.GetString("ActualPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj obrazek.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj newsa.
        /// </summary>
        public static string AddNews {
            get {
                return ResourceManager.GetString("AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj slajd.
        /// </summary>
        public static string AddSlide {
            get {
                return ResourceManager.GetString("AddSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sekcje.
        /// </summary>
        public static string AddTheSection {
            get {
                return ResourceManager.GetString("AddTheSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj podsekcje.
        /// </summary>
        public static string AddTheSubsection {
            get {
                return ResourceManager.GetString("AddTheSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie grafiki w serwisie.
        /// </summary>
        public static string AllImageInService {
            get {
                return ResourceManager.GetString("AllImageInService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie wiadomości.
        /// </summary>
        public static string AllNews {
            get {
                return ResourceManager.GetString("AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiwum według miesięcy.
        /// </summary>
        public static string Archive_by_month {
            get {
                return ResourceManager.GetString("Archive_by_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załącz obrazek.
        /// </summary>
        public static string Attach_a_picture {
            get {
                return ResourceManager.GetString("Attach_a_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prawa autorskie do marki My Little Pony: Przyjaźń to Magia należą do © Hasbro, wszystkie inne dzieła są własnością twórców.
        /// </summary>
        public static string Autorstwo {
            get {
                return ResourceManager.GetString("Autorstwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana Awatara.
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana adresu e-mail.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana loginu.
        /// </summary>
        public static string ChangeLogin {
            get {
                return ResourceManager.GetString("ChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień swój awatar.
        /// </summary>
        public static string ChangeYourAvatar {
            get {
                return ResourceManager.GetString("ChangeYourAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień swój adres e-mail.
        /// </summary>
        public static string ChangeYourEmailAdress {
            get {
                return ResourceManager.GetString("ChangeYourEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień swój login.
        /// </summary>
        public static string ChangeYourLogin {
            get {
                return ResourceManager.GetString("ChangeYourLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień swoje hasło.
        /// </summary>
        public static string changeyourpassword {
            get {
                return ResourceManager.GetString("changeyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamknij.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikat.
        /// </summary>
        public static string communicate {
            get {
                return ResourceManager.GetString("communicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź nowe hasło.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link slajdu.
        /// </summary>
        public static string ContentLink {
            get {
                return ResourceManager.GetString("ContentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść wiadomości.
        /// </summary>
        public static string ContentMessage {
            get {
                return ResourceManager.GetString("ContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść slajdu.
        /// </summary>
        public static string ContentSlide {
            get {
                return ResourceManager.GetString("ContentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokonanych zmian nie będzie można przywrócić.
        /// </summary>
        public static string DeleteComunicate {
            get {
                return ResourceManager.GetString("DeleteComunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy na pewno chcesz usunąć?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj zawartość slajdu.
        /// </summary>
        public static string EditContentSlide {
            get {
                return ResourceManager.GetString("EditContentSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj wiadomość.
        /// </summary>
        public static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj sekcje.
        /// </summary>
        public static string EditSection {
            get {
                return ResourceManager.GetString("EditSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj sekcje strony.
        /// </summary>
        public static string EditSectionSite {
            get {
                return ResourceManager.GetString("EditSectionSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail.
        /// </summary>
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string eng_lang {
            get {
                return ResourceManager.GetString("eng_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja angielska.
        /// </summary>
        public static string EnglishVersion {
            get {
                return ResourceManager.GetString("EnglishVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularz zmiany awatara.
        /// </summary>
        public static string FormChangeAvatar {
            get {
                return ResourceManager.GetString("FormChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularz zmiany adresu e-mail.
        /// </summary>
        public static string FormChangeEmailAddress {
            get {
                return ResourceManager.GetString("FormChangeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularz zmiany loginu.
        /// </summary>
        public static string FormChangeLogin {
            get {
                return ResourceManager.GetString("FormChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formularz zmainy hasła.
        /// </summary>
        public static string FormChangePassword {
            get {
                return ResourceManager.GetString("FormChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor ilustracji © Ruhisu.
        /// </summary>
        public static string Ilustracje {
            get {
                return ResourceManager.GetString("Ilustracje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrazek.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrazki.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrazek do slajdu.
        /// </summary>
        public static string ImageToSlide {
            get {
                return ResourceManager.GetString("ImageToSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zawartości newsa.
        /// </summary>
        public static string InContentNews {
            get {
                return ResourceManager.GetString("InContentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W zawartości podsekcji.
        /// </summary>
        public static string InContentSubsection {
            get {
                return ResourceManager.GetString("InContentSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W nazwie autora.
        /// </summary>
        public static string InNameAuthor {
            get {
                return ResourceManager.GetString("InNameAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W nazwie podsekcji.
        /// </summary>
        public static string InNameSubsection {
            get {
                return ResourceManager.GetString("InNameSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tytule.
        /// </summary>
        public static string InTitle {
            get {
                return ResourceManager.GetString("InTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string lang_set {
            get {
                return ResourceManager.GetString("lang_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załaduj.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załaduj obrazek:.
        /// </summary>
        public static string Load_Image {
            get {
                return ResourceManager.GetString("Load_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj treścią.
        /// </summary>
        public static string manage_content {
            get {
                return ResourceManager.GetString("manage_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj sekcjami.
        /// </summary>
        public static string ManageSections {
            get {
                return ResourceManager.GetString("ManageSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj tłumaczeniami.
        /// </summary>
        public static string ManageTranslate {
            get {
                return ResourceManager.GetString("ManageTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiadomość.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treść wiadomości.
        /// </summary>
        public static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa sekcji.
        /// </summary>
        public static string NameOfTheSection {
            get {
                return ResourceManager.GetString("NameOfTheSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa podsekcji.
        /// </summary>
        public static string NameOfTheSubsection {
            get {
                return ResourceManager.GetString("NameOfTheSubsection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy adres e-mail.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy Login.
        /// </summary>
        public static string NewLogin {
            get {
                return ResourceManager.GetString("NewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualności.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak dostępu.
        /// </summary>
        public static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nic nie znaleziono.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lub załaduj nowy.
        /// </summary>
        public static string OrAttachNewImage {
            get {
                return ResourceManager.GetString("OrAttachNewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zawartość strony.
        /// </summary>
        public static string PageContent {
            get {
                return ResourceManager.GetString("PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz uprawnień do zawartości tej podstrony..
        /// </summary>
        public static string PermissionCommunicate {
            get {
                return ResourceManager.GetString("PermissionCommunicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string pl_lang {
            get {
                return ResourceManager.GetString("pl_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja polska.
        /// </summary>
        public static string PolishVersion {
            get {
                return ResourceManager.GetString("PolishVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data publikacji.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opublikowany przez.
        /// </summary>
        public static string published_by {
            get {
                return ResourceManager.GetString("published_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czytaj więcej....
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zmiany.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukaj....
        /// </summary>
        public static string search_txt {
            get {
                return ResourceManager.GetString("search_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki wyszukiwań.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcje strony.
        /// </summary>
        public static string SectionOfTheSite {
            get {
                return ResourceManager.GetString("SectionOfTheSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz grafikę.
        /// </summary>
        public static string SelectGraphic {
            get {
                return ResourceManager.GetString("SelectGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz obrazek.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw hasło.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slajd.
        /// </summary>
        public static string Slide {
            get {
                return ResourceManager.GetString("Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slajdy.
        /// </summary>
        public static string Slides {
            get {
                return ResourceManager.GetString("Slides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagi.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagi wiadomości.
        /// </summary>
        public static string TagsMessage {
            get {
                return ResourceManager.GetString("TagsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link do podstrony odzyskiwania hasła nieistnieje.
        /// </summary>
        public static string ThePasswordRecoverySitelinkDoesNotExist {
            get {
                return ResourceManager.GetString("ThePasswordRecoverySitelinkDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryształowe Oblężenie.
        /// </summary>
        public static string TitleBook {
            get {
                return ResourceManager.GetString("TitleBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł wiadomości.
        /// </summary>
        public static string TitleMessage {
            get {
                return ResourceManager.GetString("TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kryształowe Oblężenie - Jakub Orłowski.
        /// </summary>
        public static string TitlePage {
            get {
                return ResourceManager.GetString("TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł sekcji.
        /// </summary>
        public static string TitleSection {
            get {
                return ResourceManager.GetString("TitleSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł slajdu.
        /// </summary>
        public static string TitleSlide {
            get {
                return ResourceManager.GetString("TitleSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł podsekcji.
        /// </summary>
        public static string TitleSubSection {
            get {
                return ResourceManager.GetString("TitleSubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tłumaczenia.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofnij.
        /// </summary>
        public static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikacja.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl profil.
        /// </summary>
        public static string view_profile {
            get {
                return ResourceManager.GetString("view_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl wszystkie obrazki.
        /// </summary>
        public static string ViewAllImages {
            get {
                return ResourceManager.GetString("ViewAllImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl newsy.
        /// </summary>
        public static string ViewNews {
            get {
                return ResourceManager.GetString("ViewNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl slajdy.
        /// </summary>
        public static string ViewSlides {
            get {
                return ResourceManager.GetString("ViewSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twórca serwisu © DayanDey.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdzie znaleziono.
        /// </summary>
        public static string WhereWereFound {
            get {
                return ResourceManager.GetString("WhereWereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napisz wiadomość.
        /// </summary>
        public static string WriteMessage {
            get {
                return ResourceManager.GetString("WriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje dane logowania.
        /// </summary>
        public static string YourLoginDate {
            get {
                return ResourceManager.GetString("YourLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij obrazek na stronę.
        /// </summary>
        public static string YouSendImage {
            get {
                return ResourceManager.GetString("YouSendImage", resourceCulture);
            }
        }
    }
}
